# -*- coding: utf-8 -*-
"""nifty-500-eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECdkoaaXqrFMJj251wkZDNCenLJlmxj4
"""

import numpy as np 
import pandas as pd


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")
# %matplotlib inline

df = pd.read_csv('nifty_500.csv')

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

df.nunique()

"""**Object Values**"""

object_dtype = df.select_dtypes(include=object)
object_dtype.columns

"""**Numerical Values**"""

object_dtype = df.select_dtypes(exclude=object)
object_dtype.columns

sns.distplot(x = df['Open'])

sns.distplot(x = df['High'])

sns.distplot(x = df['Open'])

sns.distplot(x = df['Previous Close'])

sns.countplot(df['Industry'])
plt.xticks(rotation=90)

sns.countplot(df['Series'])

fx = df[['High','Low']].plot(figsize=(20,7))
fx.set_title("High vs Low",fontsize=25)

fx = df[['Open','Previous Close']].plot(figsize=(20,5))
fx.set_title("Open Vs Previous Close",fontsize=20)

fx = df[['Open','Last Traded Price']].plot(figsize=(20,5))
fx.set_title("Open Vs Last Traded Price",fontsize=20)

sns.jointplot(x='Open', y='Previous Close', data=df, kind="reg", truncate=False, color="m", height=7);

sns.jointplot(x='High', y='Low', data=df, kind="reg", truncate=False, color="m", height=7);

sns.jointplot(x= 'Share Volume', y= 'Value (Indian Rupee)', data=df, kind="reg", truncate=False, color="m", height=7);

sns.jointplot(x= 'High', y= 'Value (Indian Rupee)', data=df, kind="reg", truncate=False, color="m", height=7);

sns.jointplot(x= 'Low', y= 'Value (Indian Rupee)', data=df, kind="reg", truncate=False, color="m", height=7);

sns.jointplot(x= 'Share Volume', y= 'High', data=df, kind="reg", truncate=False, color="m", height=7);

sns.jointplot(x= 'Share Volume', y= '52 Week High', data=df, kind='reg', truncate=False, color="m", height=7);

sns.pairplot(df)
plt.show()

plt.figure(figsize = (10, 10))
cor=df.corr()
sns.heatmap(cor, annot = True, cmap="YlGnBu")
plt.show()

fig, axs = plt.subplots(5, 2, figsize=(8,10))
fig.tight_layout(pad=4.0)
features = ['Open', 'High', 'Low', 'Previous Close', 'Last Traded Price','Share Volume', 'Value (Indian Rupee)', '52 Week High', '52 Week Low']
for f,ax in zip(features,axs.ravel()):
    ax=sns.boxplot(ax=ax,data=df,y=df[f])
    ax.set_title('Feature:'+ f)

df.plot(subplots=True,figsize=(29,15))

